
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/Container/Container";
import { TicketContextProvider } from "@/_context/TicketContext";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProviders/ReactQueryClientProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <title>Support Track</title>
        <meta name="description"/>
      </head>
      <ReactQueryClientProvider>
      <TicketContextProvider>
      <body className={`${inter.className}`}>
        <Container inter={inter}>{children}</Container>
      </body>
      </TicketContextProvider>
      </ReactQueryClientProvider>
    </html>
  );
}
